export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const UNSET_PRODUCT_DATA = "UNSET_PRODUCT_DATA"; 
export const SET_SEARCH_LIST = "SET_SEARCH_LIST";
export const UNSET_SEARCH_LIST = "UNSET_SEARCH_LIST";
export const SET_DATA = "SET_DATA";
export const UNSET_DATA = "UNSET_DATA"